version: '3'
services:
  db: 
    image: mariadb:10.3.2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MAGE_DB_NAME}
      - MYSQL_USER=${MAGE_DB_USER}
      - MYSQL_PASSWORD=${MAGE_DB_PASSWORD}
    restart: on-failure:5
    networks:
      - default
    volumes:
      - ./backup/sql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - 3306
  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    env_file: .env
    networks:
      - default
  app:
    image: chachakawooka/mage_stack
    volumes:
      - app_etc:/app/app/etc
      - app_pub:/app/pub
      - ./app/code:/app/app/code
      - ./app/design/frontend:/app/app/design/frontend
      - ./app/frontools:/app/dev/tools/frontools/
      - ./backup/media:/app/pub/media
    restart: on-failure:5
    env_file:
      - .env
    depends_on: 
      - db
    ports:
      - 32733:80
    networks:
      - default
volumes:
  app_etc: {}
  db: {}
  app_pub: {}