version: '3'
services:
  db: 
    image: mariadb:10.3.2
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MAGE_DB_NAME}
      - MYSQL_USER=${MAGE_DB_USER}
      - MYSQL_PASSWORD=${MAGE_DB_PASSWORD}
    restart: on-failure:5
    networks:
      - default
  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    env_file: .env
    networks:
      - default
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:${ELASTICSEARCH_VERSION}
    restart: on-failure:5
    env_file: .env
    environment:
      - discovery.type=single-node
    networks:
      - default
  app:
    image: chachakawooka/mage_stack
    volumes: 
      - ./app/code:/app/app/code
      - ./app/design/frontend:/app/app/design/frontend
    build:
      context: ./docker/stack
      args:
        - MAGENTO_COMPOSER_USER=${MAGENTO_COMPOSER_USER}
        - MAGENTO_COMPOSER_PASSWORD=${MAGENTO_COMPOSER_PASSWORD}
    restart: on-failure:5
    env_file:
      - .env
    depends_on: 
      - db
    ports:
      - 80
    networks:
      - default