version: "3"
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MAGE_DB_NAME}
      - MYSQL_USER=${MAGE_DB_USER}
      - MYSQL_PASSWORD=${MAGE_DB_PASSWORD}
    restart: on-failure:5
    networks:
      - default
    volumes:
      - ./backup/sql:/docker-entrypoint-initdb.d
      - db:/var/lib/mysql
    ports:
      - 3306
  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    env_file: .env
    networks:
      - default
  app:
    image: your_project_name/mage_stack
    build:
      context: ./
      dockerfile: Dockerfile-dev
      args:
        - MAGENTO_COMPOSER_USER=${MAGENTO_COMPOSER_USER}
        - MAGENTO_COMPOSER_PASSWORD=${MAGENTO_COMPOSER_PASSWORD}
    volumes:
      - ./app/code:/app/app/code
      - ./app/design/frontend:/app/app/design/frontend
      - ./backup/media:/app/pub/media
    restart: on-failure:5
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 32733:80
    networks:
      - default
  es01:
    image: smilesuite/es
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    build:
      context: ./
      dockerfile: Dockerfile-elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
  rabbitmq:
    image: rabbitmq:3.8-management
    ports:
      - 15672
volumes:
  db: {}
