######################
# PHP STARTING
######################
FROM chachakawooka/mage_stack:2.4.6.3

USER www-data
ARG MAGENTO_COMPOSER_USER
ARG MAGENTO_COMPOSER_PASSWORD
RUN composer config --global http-basic.repo.magento.com $MAGENTO_COMPOSER_USER $MAGENTO_COMPOSER_PASSWORD

#ADD AUTH
#RUN composer config http-basic.repo.wyomind.com {USER} {PASSWORD}

#ADD REPOS
#RUN composer config repositories.repo.wyomind.com composer https://repo.wyomind.com 

#ADD MODULES
WORKDIR /app

#SETUP SERVICES
USER root
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY custom.sh /custom.sh
RUN chmod +x /custom.sh

CMD ["/bin/bash", "/start.sh"]

HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:80/
