######################
# PHP STARTING
######################
FROM chachakawooka/mage_stack:2.4.5.1

ARG MAGENTO_COMPOSER_USER
ARG MAGENTO_COMPOSER_PASSWORD
RUN composer config --global http-basic.repo.magento.com $MAGENTO_COMPOSER_USER $MAGENTO_COMPOSER_PASSWORD

#ADD AUTH
#RUN composer config http-basic.repo.wyomind.com {USER} {PASSWORD}

#ADD REPOS
#RUN composer config repositories.repo.wyomind.com composer https://repo.wyomind.com 


#ALPACA NEED IT
RUN composer require magento/composer-root-update-plugin ~2.0 --no-update
RUN composer require snowdog/module-alpaca-packages snowdog/frontools

WORKDIR /app/vendor/snowdog/frontools
RUN /bin/bash -c "source $NVM_DIR/nvm.sh && \ 
nvm install 14 && \
nvm use 14 && \
npm install gulp -g && \
npm install && \
gulp setup"

COPY /app/frontools/config /app/dev/tools/frontools/config
COPY /app/code /app/app/code
COPY /app/design/frontend/Magestack/starter /app/app/design/frontend/Magestack/starter

#ADD MODULES
WORKDIR /app

#SETUP SERVICES
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
COPY start.sh /start.sh
RUN chmod +x /start.sh

CMD ["/bin/bash", "/start.sh"]

HEALTHCHECK --timeout=10s CMD curl --silent --fail http://127.0.0.1:80/
