version: "3"
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MAGE_DB_NAME}
      - MYSQL_USER=${MAGE_DB_USER}
      - MYSQL_PASSWORD=${MAGE_DB_PASSWORD}
    restart: on-failure:5
    networks:
      - default
  redis:
    image: redis:${REDIS_VERSION}
    restart: on-failure:5
    env_file: .env
    networks:
      - default
  es01:
    image: elasticsearch:7.17.9
    restart: on-failure:5
    env_file: .env
    environment:
      - node.name=es01
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    networks:
      - default
  app:
    image: chachakawooka/mage_stack
    volumes:
      - ./app/code:/app/app/code
      - ./app/design/frontend:/app/app/design/frontend
    build:
      context: ./docker/stack
      args:
        - MAGENTO_COMPOSER_USER=${MAGENTO_COMPOSER_USER}
        - MAGENTO_COMPOSER_PASSWORD=${MAGENTO_COMPOSER_PASSWORD}
    restart: on-failure:5
    env_file:
      - .env
    depends_on:
      - db
    ports:
      - 32733:80
    networks:
      - default
