version: '3'
services:
  app:
    volumes:
      - migration-app:/app
      - ./additionals/ub-tool/Ubertheme:/app/app/code/Ubertheme
  ubertool:
    image: nginx
    ports:
      - "32734:80"
    volumes:
      - migration-app:/app
      - ./additionals/ub-tool/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on: 
      - app
      - m1db
  m1db: 
    image: mariadb:10.3.2
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=magento1
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
    restart: on-failure:5
    volumes:
      - ./additionals/ub-tool/sql:/docker-entrypoint-initdb.d
    networks:
      - default

volumes:
  migration-app: {}